#Using this version to prevent an error upon exiting. Unsure if I need to update & figure out why npm wants to scream at me
FROM node:20.11.1-bullseye-slim

WORKDIR /client

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 8080

CMD [ "npm", "run", "preview" ]