services:
- type: web
  name: RetroMOOapi
  runtime: docker
  repo: https://github.com/Tomaster134/RetroMOO
  branch: main
  plan: free
  envVars:
  - key: SQLALCHEMY_DATABASE_URI
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: FLASK_APP
    sync: false
  region: ohio
  dockerContext: .
  dockerfilePath: Dockerfile.api
  rootDir: api
version: "1"

- type: web
  name: RetroMOO
  runtime: docker
  repo: https://github.com/Tomaster134/RetroMOO
  branch: main
  plan: free
  region: ohio
  dockerContext: .
  dockerfilePath: Dockerfile.client
  rootDir: client
version: "1"
