npc_dict = {
    'Crier': {
        'name': 'Bob, the Town Crier',
        'aliases': ['Bob', 'Crier', 'The Town Crier'],
        'description': 'A young man dressed in common clothing, looking about as if to see who he\'ll announce the latest news to.',
        'location': '0,0',
        'home': '0,0',
        'deceased': False,
        'health': 100,
        'level': 1,
        'ambiance_list': ['The Town Crier yells "Murder in the forest! B\'ware!"', 'The Town Crier yawns and scratches himself.','You hear the Town Crier mutter "Why is it always murder? Nobody ever wants to hear about the ducks."'],
        'can_wander': True,
        'attackable': True,
    },
    'Mayor': {
        'name': 'The Mayor',
        'aliases': ['The Mayor', 'Mayor', 'Boss', 'Head Honcho'],
        'description': 'A truly corpulent man, grown large on the wealth of others. His fingers are clad with more rings than you can count, and his clothing is of the finest make. Honestly, it seems a little overkill.',
        'location': 'Mayoral Mansion',
        'home': 'Mayoral Mansion',
        'deceased': False,
        'health': 200,
        'level': 10,
        'ambiance_list': ['The Mayor snaps at a servant, demanding wine.', 'The Mayor chuckles to himself, at a joke only he knows.', 'The Mayor looks askance at the dirt you tracked in from the outdoors.'],
        'can_wander': False,
        'attackable': True,
    },
     'Mercenary': {
        'name': 'Thor, the Local Mercenary',
        'aliases': ['Merc', 'Mercenary', 'The Local Mercenary', 'Thor', 'Dragonborn'],
        'description': 'A fearsome Emerald Dragonborn, clad in furs. Two wicked axes adorn his back.',
        'location': '-1,0',
        'home': '-1,0',
        'deceased': False,
        'health': 100,
        'level': 1,
        'ambiance_list': ['The Mercenary mutters to himself at your glance, "Newbies never seen dragons blood before?"'],
        'can_wander': False,
        'attackable': True,
    },
    'Snotty Adolescent': {
        'name': 'Billy',
        'aliases': ['billy', 'kid', 'snotty', 'dirty',],
        'description': 'A scrawny teenager, covered in dirt and god knows what else. He\'s currently playing a dead rat. You\'re mildly worried for his mental health.',
        'location': '1,1',
        'home': '1,1',
        'deceased': False,
        'health': 10,
        'level': 1,
        'ambiance_list': ['You see Billy pushing something around in the muck in front of the general store.', 'Billy sticks his tongue out at your and blows a raspberry.', 'Billy runs up to you and wipes his hands on your shirt. Whatever was on his hands certainly isn\'t sanitary.'],
        'can_wander': True,
        'attackable': False,
    },
    'Wise Man': {
        'name': 'Old Wise Man',
        'aliases': ['old', 'wise', 'man', 'old wise man', 'geezer', 'old man'],
        'description': 'Hunched over and wearing a rough spun robe, this guy has seen it all. He looks like he has some good advice, should you be willing to listen.',
        'location': '-1,-1',
        'home': '-1,-1',
        'deceased': False,
        'health': 10,
        'level': 1,
        'ambiance_list': ['The old man takes a deep breath. You wonder what he ponders.', 'The old man looks at you, eyebrows raised. "Would ya like a candy, son?" he asks.', 'You hear the old man mutter something about the inevitability of violence.'],
        'can_wander': False,
        'attackable': True,
    },
    'Stooge 1': {
        'name': 'Curly',
        'aliases': ['curly', 'idiot'],
        'description': 'The youngest of 3 brothers. Dressed in poorly fitting armor, he stares at you with a vacant expression on his face.',
        'location': 'Barracks Interior',
        'home': 'Barracks Interior',
        'deceased': False,
        'health': 100,
        'level': 2,
        'ambiance_list': ['Curly digs deep into his nose. It doesn\'t look like he\'s washed his hands in some time.', 'Curly lets loose a large belch.', 'Curly nudges one of his brothers, who gives him a glare.'],
        'can_wander': False,
        'attackable': True,
    },
    'Stooge 2': {
        'name': 'Whirly',
        'aliases': ['whirly', 'devious'],
        'description': 'The middle of 3 brothers. His eyes are constantly darting around, and he has a nervous expression on his face. He reminds you of a rat.',
        'location': 'Barracks Interior',
        'home': 'Barracks Interior',
        'deceased': False,
        'health': 100,
        'level': 2,
        'ambiance_list': ['A loud bang is heard from upstairs, and you see Whirly flinch.', 'A small rodent scurries across the floor. You\'re struck by its resemblence to Whirly.', 'You hear Whirly muttering to himself.'],
        'can_wander': False,
        'attackable': True,
    },
    'Stooge 3': {
        'name': 'Joe',
        'aliases': ['joe', 'big guy'],
        'description': 'The oldest of 3 brothers. You can\'t believe he\'s actually human. His grandmother must have found an orc particularly attractive, because he looks like he weighs 400 pounds and is rippling with muscles. It looks like even his eyebrows could bench press you.',
        'location': 'Barracks Interior',
        'home': 'Barracks Interior',
        'deceased': False,
        'health': 100,
        'level': 2,
        'ambiance_list': ['Joe looks directly at you, unblinking. You are slightly unsettled.', 'Joe walks over to a sack of sand that looks like it weighs 500 pounds and casually does some squats with it.', 'Joe jumps up and down, warming up. You can swear you heard a floorboard crack from his weight.'],
        'can_wander': False,
        'attackable': True,
    },
}